# Generated by Django 3.2.5 on 2021-11-15 13:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Title')),
                ('subject_teacher', models.CharField(max_length=50, verbose_name='Teacher')),
                ('subject_star', models.FloatField(default=0, null=True, verbose_name='Star')),
                ('subject_credit', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=400, verbose_name='Text')),
                ('comment_star', models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment_starWidth', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('writer_id', models.PositiveIntegerField(default=1)),
                ('writer_generation', models.PositiveIntegerField(default=1)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeclStar_1st.subject_1')),
            ],
        ),
    ]
