# Generated by Django 3.2.5 on 2021-11-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Title')),
                ('subject_teacher', models.CharField(max_length=50, verbose_name='Teacher')),
                ('subject_star', models.FloatField(default=0, null=True, verbose_name='Star')),
            ],
        ),
    ]
