# Generated by Django 3.2.5 on 2021-11-12 08:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeclStar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=400, verbose_name='Text')),
                ('comment_star', models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeclStar.subject')),
            ],
        ),
    ]
