# Generated by Django 3.2.5 on 2021-11-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeclStar', '0003_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_starWidth',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
