# Generated by Django 3.2.5 on 2021-11-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeclStar', '0005_auto_20211115_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_credit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
