# Generated by Django 3.2.5 on 2021-11-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeclStar', '0006_subject_subject_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_semester',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
