# Generated by Django 3.2.5 on 2021-11-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeclBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='writer_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
